---
- hosts: all
  become: true
  become_user: root

  tasks:
  - user:
    name: bmetcalf
    password: "$1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI."
    groups: wheel

  - name: Set authorized key took from file
    authorized_key:
      user: bmetcalf
      state: present
      key: "{{ lookup('file', '/home/bmetcalf/.ssh/id_rsa.pub') }}"


